generate uuids to be used internally based on shasums of machine-id

diff --git a/bin/cicdaemon b/bin/cicdaemon
--- a/bin/cicdaemon
+++ b/bin/cicdaemon
@@ -36,9 +36,16 @@ DEV=true
 [ ! -d $WORK_DIR ] && mkdir -p /opt/cicdaemon/log
 
 #reset and log /etc/machine-id and re-link /var/lib/dbus/machine-id to it
+#on the template, /etc/machine-id should be empty
+#CIC_UUID is the sha1 checksum of the machine-id
 if systemd-machine-id-setup; then
-	log info "Generated new machine id: [$(cat /etc/machine-id)]"
-	if ln -s /etc/machine-id /var/lib/dbus/machine-id; then :
-	else log error "Failed to symlink /etc/machine-id to /var/lib/dbus/machine-id"; exit 1
+	 log info "Generated new machine id: [$(cat /etc/machine-id)]"
+	if ln -s /etc/machine-id /var/lib/dbus/machine-id; then
+		 CIC_UUID=$( shasum -a 1  /etc/machine-id | awk '{print $1}' )
+		 log info "Generated CIC_UUID: [$CIC_UUID]"
+		 xattr -w trusted.cicdaemon.sha1 "$CIC_UUID"
+		 echo "$CIC_UUID" > /etc/cic-id
 	fi
+else 
+	log error "Failed to symlink /etc/machine-id to /var/lib/dbus/machine-id"; exit 1
 fi
